export const voiceModel=process.env.REALTIME_MODEL||'gpt-realtime';
export const voiceSession=mode=>({
 type:'realtime',model:voiceModel,output_modalities:['audio'],
 instructions:`You are a live design partner working alongside the user in ${mode==='studio'?'Blender':'Excalidraw'}. Their iPhone points at the actual workspace. ALWAYS speak English, even if input or transcription is in another language. Do not imitate another language. Discuss the actual objects, connections and design; never announce that this is an Excalidraw drawing or describe the editor as the result. Ignore background speech, noise and uncertain audio rather than inventing a task. For an edit, call edit_workspace immediately so drawing work starts without waiting for speech. In the same response, if possible, say one short specific acknowledgment in future tense (e.g. "I'll spread these racks out and straighten the connections."). Do not wait for the tool result to acknowledge. The app supplies an acknowledgment if you only emit a tool call. Keep talking naturally when asked a question while work is pending. Use inspect_workspace to see or discuss the current objects without changing them. Use edit_workspace for EVERY request to create, build, draw, remove or modify something, including short follow-ups. Never claim to have built something without an applied edit receipt. If a tool reports no changes, failure or stopped work, say so. Use edit_workspace for edits; it delegates to GPT-6 Astra with live pointer/selection. Preserve the user's request exactly and succinctly. Never invent requirements, node counts, capacities, labels, or additions while forwarding it. Acknowledgments like "okay" or "hmm" are not new edit requests. Answer status questions about pending work from the conversation; do not restart the edit. A correction such as "actually only two" must call edit_workspace directly with the complete revised request; this automatically stops and replaces earlier work. Do not call stop_edit as a preliminary step for a correction. Use stop_edit only for an explicit request to stop with no replacement. For "undo" or "undo your last change", always call undo_workspace. Never reconstruct the prior design with edit_workspace. Never claim a change before its successful result. When finished, briefly explain the useful result or one design choice, not a generic "done". Avoid claiming you can see details not supplied by a tool.`,
 audio:{input:{transcription:{model:'gpt-4o-mini-transcribe',language:'en',prompt:'The user speaks English about designing diagrams. Transcribe English speech; do not translate it.'},turn_detection:{type:'server_vad',threshold:0.5,prefix_padding_ms:300,silence_duration_ms:350,create_response:true,interrupt_response:true}},output:{voice:'marin'}},
 tools:[{type:'function',name:'inspect_workspace',description:'Read the current objects, labels, selection and pointer without modifying anything. Use for questions about the design.',parameters:{type:'object',properties:{},additionalProperties:false}},{type:'function',name:'edit_workspace',description:'Ask Astra to create or modify actual scene objects using the live phone pointer and current selection. Use for every requested edit; use inspect_workspace for read-only questions.',parameters:{type:'object',properties:{request:{type:'string'}},required:['request'],additionalProperties:false}},{type:'function',name:'undo_workspace',description:'Undo the last assistant edit using the editor history. Restores original geometry and preserves unrelated user edits. Always use this for Undo; never ask edit_workspace to recreate the previous design.',parameters:{type:'object',properties:{},additionalProperties:false}},{type:'function',name:'stop_edit',description:'Stop without a replacement. For corrections use edit_workspace directly, which replaces the running edit automatically.',parameters:{type:'object',properties:{},additionalProperties:false}}],tool_choice:'auto',max_output_tokens:600,
});
export async function createVoiceCall(sdp,mode){
 if(!process.env.OPENAI_API_KEY)throw Error('OpenAI key is not connected');
 const body=new FormData();body.set('sdp',sdp);body.set('session',JSON.stringify(voiceSession(mode)));
 const response=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body,signal:AbortSignal.timeout(30000)});
 if(!response.ok){const error=await response.json().catch(()=>({}));throw Error(String(error.error?.message||`Realtime returned ${response.status}`).replace(/sk-[A-Za-z0-9_.*-]+/g,'[redacted key]'))}
 return response.text();
}
