import {WebSocketServer} from 'ws';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {diagramEdit} from '../native/diagram.mjs';
const server=new WebSocketServer({port:4312,host:'127.0.0.1'});let socket,id=0;const pending=new Map();
server.on('connection',(ws,req)=>{if(req.headers.origin!=='http://127.0.0.1:3010'){ws.close();return;}socket=ws;ws.on('message',raw=>{const m=JSON.parse(raw);if(pending.has(m.id)){const [resolve,reject]=pending.get(m.id);pending.delete(m.id);m.error?reject(Error(m.error)):resolve(m.result);}});});
const call=message=>new Promise((resolve,reject)=>{pending.set(++id,[resolve,reject]);socket.send(JSON.stringify({id,...message}));});
console.log('Reload validation renderer');while(!socket)await new Promise(r=>setTimeout(r,100));await new Promise(r=>setTimeout(r,600));
const scene=await call({action:'reset'});
const result=await call({action:'edit',...diagramEdit({nodes:[{id:'backend',label:'Backend Server',kind:'service'},...[1,2,3].map(i=>({id:'gpu'+i,label:'GPU Rack '+i,kind:'compute'}))],edges:[1,2,3].map(i=>({from:'backend',to:'gpu'+i}))},scene)});
const labels=result.elements.filter(e=>e.type==='text'&&e.text.startsWith('GPU')).sort((a,b)=>a.x-b.x);assert.deepEqual(labels.map(e=>e.text),['GPU Rack 1','GPU Rack 2','GPU Rack 3']);
const view=await call({action:'image'});await fs.writeFile('../excalidraw/validation/partner-layout.png',Buffer.from(view.image.split(',')[1],'base64'));
await fs.writeFile('../excalidraw/validation/partner-layout.excalidraw',JSON.stringify({type:'excalidraw',version:2,elements:result.elements,appState:{viewBackgroundColor:'#fcfbf8'},files:{}}));
console.log('PASS actual renderer: sibling order and bindings');socket.close();server.close();
