import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import ts from 'typescript';
import {readResponse} from '../native/response-stream.mjs';
import {sceneContext} from '../native/scene-context.mjs';
import {diagramEdit} from '../native/diagram.mjs';
const encoder=new TextEncoder();
const events=[{type:'response.output_item.done',item:{id:'one',type:'function_call',call_id:'c',arguments:'{}'}},{type:'response.output_item.done',item:{id:'one',type:'function_call',call_id:'c',arguments:'{}'}},{type:'response.completed',response:{id:'resp',output:[]}}];
const bytes=encoder.encode(events.map(e=>'data: '+JSON.stringify(e)+'\r\n\r\n').join(''));
let completed=false,calls=0;
await readResponse(new Response(new ReadableStream({async start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close();}})),{onItem:async()=>{assert(!completed);calls++;}});completed=true;assert.equal(calls,1);
await assert.rejects(readResponse(new Response('data: {"type":"response.failed","response":{"error":{"message":"failed"}}}\n\n')),/failed/);
// A completed response must return even if transport cancellation never resolves.
const slowCleanup=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('data: {"type":"response.completed","response":{"id":"complete"}}\n\n'));},cancel(){return new Promise(()=>{});}});
let cleanupTimer;
try{assert.equal((await Promise.race([readResponse(new Response(slowCleanup)),new Promise((_,reject)=>{cleanupTimer=setTimeout(()=>reject(Error('Completed response blocked on stream cleanup')),250);})])).id,'complete');}finally{clearTimeout(cleanupTimer);}
const abort=new AbortController();abort.abort();await assert.rejects(readResponse(new Response('data: {"type":"response.completed"}\n\n'),{signal:abort.signal}),{name:'AbortError'});
const scene={revision:1,elements:[{id:'a',type:'rectangle',x:0,y:0,width:200,height:80,seed:100,boundElements:[{id:'text',type:'text'}]},{id:'text',type:'text',text:'API',containerId:'a'}],selected:['a'],pointer:{scene:{x:100,y:40}}};
assert.equal(sceneContext(scene).elements[0].label.text,'API');assert.equal(sceneContext(scene).elements[0].seed,undefined);assert.equal(scene.elements[0].seed,100);
const diagram=diagramEdit({nodes:[{id:'api',label:'API'},{id:'gpu1',label:'GPU rack 1'},{id:'gpu2',label:'GPU rack 2'}],edges:[{from:'api',to:'gpu1'},{from:'api',to:'gpu2'}]}, {revision:0,elements:[]});
const boxes=diagram.add.filter(e=>e.type==='rectangle');assert.equal(boxes.length,3);assert(boxes[1].x<boxes[2].x,'Sibling order must follow the requested labels');assert.equal(diagram.add.filter(e=>e.type==='arrow').length,2);assert.throws(()=>diagramEdit({nodes:[{id:'a',label:'A'}],edges:[{from:'a',to:'unknown'}]},scene),/absent/);
const source=await fs.readFile(new URL('../lib/voice.ts',import.meta.url),'utf8');
const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {LiveVoice}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
let interrupts=0,resolveTool;const sent=[];
const client=new LiveVoice('test',()=>{},()=>{},()=>interrupts++);client.dc={readyState:'open',send:s=>sent.push(JSON.parse(s)),close:()=>{}};
globalThis.fetch=async()=>new Response(new ReadableStream({start(c){resolveTool=()=>{c.enqueue(encoder.encode(JSON.stringify({type:'complete',result:{result:'Applied'}})+'\n'));c.close();};}}),{headers:{'content-type':'application/x-ndjson'}});
await client.event({type:'input_audio_buffer.speech_started'},0);assert.equal(interrupts,0);
await client.event({type:'input_audio_buffer.speech_stopped'},0);
await client.event({type:'response.created',response:{id:'r1'}},0);
const work=client.event({type:'response.function_call_arguments.done',response_id:'r1',call_id:'call1',name:'edit_workspace',arguments:'{"request":"Make this blue"}'},0);
await client.event({type:'response.done',response:{id:'r1'}},0);
assert(sent.some(e=>e.type==='response.create'&&e.response?.conversation==='none'),'Narration must start while the tool is pending');
await client.event({type:'response.created',response:{id:'n',metadata:{purpose:'design-progress',turn:'1'}}},0);
await client.event({type:'response.done',response:{id:'n'}},0);
await client.event({type:'input_audio_buffer.speech_started'},0);await client.event({type:'input_audio_buffer.speech_stopped'},0);
assert.equal(interrupts,0);resolveTool();await work;
assert(sent.some(e=>e.type==='conversation.item.create'&&e.item.call_id==='call1'));
assert(sent.some(e=>e.type==='response.create'&&e.response?.tool_choice==='none'&&!e.response?.metadata),'Completion must still speak after a backchannel');
client.stop();
console.log('PASS streamed tools, cancellation, compact context, graph layout, speech backchannels, narration during work and completion after backchannel');
