import assert from 'node:assert/strict';
process.env.OPENAI_API_KEY='test-key-not-a-credential';
const {createPartner}=await import('../native/model.mjs');
let round=0;
const sse=items=>new Response(items.map(item=>'data: '+JSON.stringify({type:'response.output_item.done',item})+'\n\n').join('')+'data: '+JSON.stringify({type:'response.completed',response:{id:'r'+round,output:items}})+'\n\n');
globalThis.fetch=async()=>{round++;return round===1?sse([{id:'call',type:'function_call',call_id:'c',name:'canvas',arguments:'{"revision":1,"add":[]}'}]):sse([{id:'m',type:'message',content:[{type:'output_text',text:'I built it.'}]}]);};
let messages=[];
const partner=createPartner({event:(role,text)=>{if(role==='assistant')messages.push(text)},tool:async()=>({revision:1,elements:[]})});
const result=await partner.run('Build a box','canvas',()=>{},{expectEdit:true});
assert.equal(result.status,'no_changes');assert.equal(result.appliedEdits,0);assert(!messages.includes('I built it.'));
console.log('PASS missing renderer receipt cannot produce a successful completion or forwarded success claim');
